### ISSUE TITLE
Regression from introduction of posix_spawn_file_actions_addchdir_np: `subprocess.h: error: 'posix_spawn_file_actions_addchdir_np' was not declared in this scope; did you mean 'posix_spawn_file_actions_addopen'?`

### ISSUE THREAD

**Issue by barracuda156** [sheredom/subprocess.h#108]
Regression from https://github.com/sheredom/subprocess.h/pull/83 that unconditionally added non-portable `posix_spawn_file_actions_addchdir_np`.

Has broken `llama.cpp`:
```
:info:build [ 43%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/mtmd-helper.cpp.o
:info:build cd /opt/local/var/macports/build/llama.cpp-b7053e9e/work/build/tools/mtmd && /opt/local/bin/g++-mp-16 -DGGML_BACKEND_SHARED -DGGML_SHARED -DGGML_USE_BLAS -DGGML_USE_CPU -DLLAMA_BUILD -DLLAMA_SHARED -DMTMD_VIDEO -Dmtmd_EXPORTS -I/opt/local/var/macports/build/llama.cpp-b7053e9e/work/llama.cpp-10298/tools/mtmd/. -I/opt/local/var/macports/build/llama.cpp-b7053e9e/work/llama.cpp-10298/tools/mtmd/../.. -I/opt/local/var/macports/build/llama.cpp-b7053e9e/work/llama.cpp-10298/tools/mtmd/../../vendor -I/opt/local/var/macports/build/llama.cpp-b7053e9e/work/llama.cpp-10298/ggml/src/../include -I/opt/local/var/macports/build/llama.cpp-b7053e9e/work/llama.cpp-10298/src/../include -pipe -Os -fpermissive -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -DCPPHTTPLIB_DISABLE_MACOSX_AUTOMATIC_ROOT_CERTIFICATES -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -mmacosx-version-min=10.6 -fPIC -Wmissing-declarations -Wmissing-noreturn -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-array-bounds -Wextra-semi -Wno-cast-qual -MD -MT tools/mtmd/CMakeFiles/mtmd.dir/mtmd-helper.cpp.o -MF CMakeFiles/mtmd.dir/mtmd-helper.cpp.o.d -o CMakeFiles/mtmd.dir/mtmd-helper.cpp.o -c /opt/local/var/macports/build/llama.cpp-b7053e9e/work/llama.cpp-10298/tools/mtmd/mtmd-helper.cpp
:info:build In file included from /opt/local/var/macports/build/llama.cpp-b7053e9e/work/llama.cpp-10298/tools/mtmd/mtmd-helper.cpp:41:
:info:build /opt/local/var/macports/build/llama.cpp-b7053e9e/work/llama.cpp-10298/tools/mtmd/../../vendor/sheredom/subprocess.h: In function 'int subprocess_create_ex(const char* const*, int, const char* const*, const char*, subprocess_s*)':
:info:build /opt/local/var/macports/build/llama.cpp-b7053e9e/work/llama.cpp-10298/tools/mtmd/../../vendor/sheredom/subprocess.h:1251:19: error: 'posix_spawn_file_actions_addchdir_np' was not declared in this scope; did you mean 'posix_spawn_file_actions_addopen'?
:info:build  1251 |     posix_error = posix_spawn_file_actions_addchdir_np(&actions, process_cwd);
:info:build       |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:info:build       |                   posix_spawn_file_actions_addopen
:info:build make[2]: *** [tools/mtmd/CMakeFiles/mtmd.dir/mtmd-helper.cpp.o] Error 1
:info:build make[2]: Leaving directory `/opt/local/var/macports/build/llama.cpp-b7053e9e/work/build'
:info:build make[1]: *** [tools/mtmd/CMakeFiles/mtmd.dir/all] Error 2
:info:build make[1]: *** Waiting for unfinished jobs....
```

**Comment by barracuda156** [comment]
SDL, for example, does this conditionally, and the code compiles fine on all macOS versions: https://github.com/libsdl-org/SDL/blob/56ef0efc20f0142b99e2b6147b18a26b285208e0/src/process/posix/SDL_posixprocess.c#L203-L223
