### PR TITLE
Fix building against glibc older than 2.29

### PR DESCRIPTION
**Pull request by bernardladenthin**
## Problem

`subprocess.h` does not compile on glibc older than 2.29 once `subprocess_create_ex` is
used. `posix_spawn_file_actions_addchdir_np` (added by #83, macOS branch added by #99)
only exists from glibc 2.29 onwards, and the POSIX path calls it unconditionally.

On manylinux2014 (CentOS 7, glibc 2.17, devtoolset-10 / GCC 10.2) the failure appears in
three shapes depending on the language mode:

```
C++    subprocess.h:1215: error: 'posix_spawn_file_actions_addchdir_np' was not declared in this scope
C11    subprocess.h:1215: error: implicit declaration of function ... [-Werror=implicit-function-declaration]
gnu89  ld: undefined reference to `posix_spawn_file_actions_addchdir_np'
```

The third one matters: in `gnu89` the implicit declaration is only a warning, so the
compiler is happy and the **linker** fails instead. The symbol is genuinely absent from
`libc.so`. This is therefore not the `_GNU_SOURCE` visibility issue that
`test/CMakeLists.txt` already works around — no feature-test macro can conjure a symbol
that does not exist.

Affected in practice: manylinux2014 (glibc 2.17) and manylinux_2_28 (glibc 2.28), i.e. the
standard build environments for redistributable Linux binaries. llama.cpp vendors this
header, so its manylinux jobs hit this too.

## Fix

Add a `SUBPROCESS_HAVE_CWD` compile-time probe next to the POSIX includes, and report a
requested `process_cwd` as `ENOSYS` where the platform cannot honour it. The `cwd` test is
compiled only where the capability exists.

Four deliberate choices:

- **Named after the capability, not the glibc symbol.** Users care whether they may pass a
  `cwd`, not how it is implemented.
- **Defined on every platform**, not only under `#if !defined(_WIN32)`. An undefined macro
  evaluates to 0 inside `#if`, which would have silently dropped the test on Windows.
- **Nested `#if`, not `#if defined(__GLIBC__) && !__GLIBC_PREREQ(2, 29)`.** The
  preprocessor replaces unknown identifiers with `0` before evaluating, so the flat form
  becomes `0 (2, 29)` — a syntax error on macOS, musl and Windows. `&&` does not help,
  because this fails at parse time, not evaluation time.
- **Overridable.** The detection is skipped when the macro is already defined, so platforms
  it cannot recognise are not stuck with the wrong answer. See the limitation below.

Behaviour on glibc >= 2.29 and on every non-glibc platform is byte-for-byte unchanged.
The macro is documented in `README.md` next to the `process_cwd` argument.

## Testing

Full test suite in Docker, one container per row, sanitizer probes pinned off for
reproducibility. Windows was built natively with MSVC.

| Environment | libc | Compiler | `SUBPROCESS_HAVE_CWD` | Test cases | Result |
|---|---|---|---|---|---|
| manylinux2014 | glibc 2.17 | GCC 10.2 | 0 | 423 | 405 pass, 18 fail (see below) |
| AlmaLinux 8 | glibc 2.28 | clang 21.1 | 0 | 423 | **423 pass** |
| Fedora 30 | glibc 2.29 | GCC 9.3 | 1 | header only | **builds** |
| Debian 11 | glibc 2.31 | GCC 10.2 | 1 | 432 | **432 pass** |
| Ubuntu 24.04 | glibc 2.39 | GCC 13.3 | 1 | 432 | **432 pass** |
| Ubuntu 24.04 | glibc 2.39 | clang 18.1 | 1 | 432 | **432 pass** |
| Ubuntu 24.04 | glibc 2.39 | tcc 0.9.27 | 1 | header only | **builds** |
| Alpine 3.20 | musl 1.2 | GCC 13.2 | 1 | 432 | **432 pass** |
| Alpine 3.10 | musl 1.1.22 | GCC 8.3 | 1 | header only | link error (see below) |
| Windows (cross) | — | mingw-w64 GCC 13 | 1 | compile-time assert | **holds** |
| Windows (native) | UCRT | MSVC 19.44 | 1 | 387 | **387 pass** |

Before this change, the first two rows do not build at all.

The 2.29 boundary is hit exactly: 2.28 → 0, 2.29 → 1, 2.31 → 1. The 9 `cwd` test cases are
excluded only where the function is missing — all 432 are still compiled and green
everywhere else, including musl, where the `#else` branch applies. On Windows all 9 are
present and pass; the total of 387 there is 432 minus the 45 cases (5 tests x 9 language
modes) that `test_shared.h` already excludes under `#if !defined(_MSC_VER)`.

macOS was not tested locally — CI covers it.

## Limitation: musl older than 1.1.24

musl gained `posix_spawn_file_actions_addchdir_np` in 1.1.24, so the `#else` branch is
wrong for releases before that: Alpine 3.10 (musl 1.1.22) still fails to link. musl
deliberately exposes no version macro, so this cannot be detected. That is what the
override is for — `-DSUBPROCESS_HAVE_CWD=0` builds cleanly there, verified.

## Pre-existing failures on glibc 2.17, unrelated to this change

The 18 remaining failures on manylinux2014 are `create_ex_subprocess_create_failure_preserves_error`
and `create_ex_subprocess_create_failure_does_not_leak_resources` across the 9 language
modes. They expect `subprocess_error_not_found` and get `0`.

The cause is in glibc, not in this library. A standalone probe on the same image:

```
posix_spawn  -> rc=0   child exited 127
posix_spawnp -> rc=0   child exited 127
```

Old `posix_spawn` does not report a failed `exec` back to the caller; glibc reworked this
in 2.24 — the same probe returns `rc=0` on 2.17 and 2.23, and `rc=2` on 2.24 and 2.28.
AlmaLinux 8 (glibc 2.28) shows the same `SUBPROCESS_HAVE_CWD=0` code path with
zero failures, which isolates it cleanly. These failures were simply never observable
before, because the library did not build there at all. Not addressed here.

## Also noticed

`test/CMakeLists.txt` passes `-std=c++20`, which GCC 8 (the RHEL 8 system compiler) rejects
in favour of `-std=c++2a` — the suite cannot be built with it, though the library itself
compiles fine. Not touched here; #105 fixes it separately.

### CODE REVIEW

**Comment by barracuda156** [comment]
@bernardladenthin We also need this for macOS: https://github.com/sheredom/subprocess.h/issues/108

**Comment by bernardladenthin** [comment]
> @bernardladenthin We also need this for macOS: #108

done 😃

**Comment by bernardladenthin** [comment]
@barracuda156 Thanks for the pointer and #108 is now handled in this PR.

The probe gained a Darwin arm:

```c
#elif defined(__APPLE__) && MAC_OS_X_VERSION_MIN_REQUIRED < 101500
#define SUBPROCESS_HAVE_CWD 0
```

Apple's SDKs put the boundary at exactly 10.15, and mark the call unavailable on iOS,
tvOS and watchOS outright:

```c
int     posix_spawn_file_actions_addchdir_np(posix_spawn_file_actions_t *,
    const char * __restrict) __API_AVAILABLE(macos(10.15)) __API_UNAVAILABLE(ios, tvos, watchos);
```

Where the capability is missing, a requested `process_cwd` now returns `ENOSYS` instead of
calling a function that is not there.

There is deliberately **no** `defined(MAC_OS_X_VERSION_MIN_REQUIRED)` guard on that
condition. An absent macro folds to `0`, and `0 < 101500` is true, so a toolchain that does
not supply the macro answers "no cwd" rather than optimistically assuming the call exists.
That should cover your setup even though MacPorts GCC does not define `__APPLE_CC__`, which
is what older `AvailabilityMacros.h` gates the macro on.

**That last part is the one thing I could not verify.** I tested against real 10.14, 10.15
and 15.5 SDKs with clang, cross-compiled from Linux, and reproduced #108 exactly on the
pre-10.15 SDKs — but there is no usable PowerPC-Darwin cross toolchain, so `-arch ppc` with
GCC 16 is untested. Since that is precisely your configuration, would you mind running the
counter-check?

Two questions, if you can spare the time:

1. Does the branch build for you now?

2. What does the probe actually evaluate to on your setup?

   ```sh
   printf '#include "subprocess.h"\nPROBE SUBPROCESS_HAVE_CWD\n' > /tmp/p.cpp
   g++-mp-16 -arch ppc -mmacosx-version-min=10.6 -I<path-to-header> -E /tmp/p.cpp | tail -1
   ```

   It should print `PROBE 0`. If it prints `PROBE 1`, the version macro is resolving to
   something unexpected and I would like to see what:

   ```sh
   printf '#include <AvailabilityMacros.h>\nV MAC_OS_X_VERSION_MIN_REQUIRED\n' > /tmp/av
   g++-mp-16 -arch ppc -mmacosx-version-min=10.6 -E /tmp/av.c | tail -1
   ```

Either way `-DSUBPROCESS_HAVE_CWD=0` is available as an escape hatch, but I would rather
the detection got it right on its own.

File: subprocess.h
Comment (sheredom) [inline subprocess.h:1243]: Don't we need to make `subprocess_error_from_errno` handle `ENOSYS` too?

**Comment by sheredom** [comment]
Your LLM should be made to be succinct, that is a wall of text with about 1/100 useful words.

File: subprocess.h [hunk 1]
```diff
@@ -274,6 +274,25 @@ subprocess_weak int subprocess_alive(struct subprocess_s *const process);
 #include <unistd.h>
 #endif
 
+/* Whether subprocess_create_ex can honour process_cwd. glibc only gained
+   posix_spawn_file_actions_addchdir_np in 2.29, and macOS in 10.15; the SDKs
+   mark it unavailable on iOS, tvOS and watchOS, where the undefined version
+   macro folds to 0 and so answers correctly. Define this yourself to override
+   the detection, for instance on musl older than 1.1.24. */
+#if !defined(SUBPROCESS_HAVE_CWD)
```
Comment (sheredom) [inline subprocess.h:282]: We don't need this new define - just add it inline where you set `ENOSYS`.

**Comment by sheredom** [comment]
Is there anyway we can test this in CI? I'd love not to regress y'all in future!

File: subprocess.h (hunk 1 above)
Comment (sheredom) [reply subprocess.h:282]: Changed my mind actually - you are right to add the define for the testing too. I generally dislike defines s'all!

**Comment by bernardladenthin** [comment]
On length: I do prefer recording what was tested, why, and what wasn't - it saves the
next person redoing it. But you're right that it needs a tl;dr up front, I'll lead with
one from now on.

On the override: it isn't there because of how I tested, it's there because musl exposes
no version macro, so releases before 1.1.24 can't be detected at all. `-DSUBPROCESS_HAVE_CWD=0`
is the only way out for those users. glibc, macOS and iOS are all detected automatically;
the override is just the escape hatch for platforms the probe can't recognise.

On CI: happy to set it up if you want it. Two things are straightforward:

- **Linux** — a Docker matrix across glibc 2.17 / 2.28 / 2.29 / 2.31 and musl, which pins
  the 2.29 boundary from both sides.
- **macOS** — on the existing runner, no extra SDK needed: build with
  `-mmacosx-version-min=10.13 -Werror=unguarded-availability-new`. I verified that this
  fails on `main` and passes on this branch, so it would have caught the original
  regression.

What can't be done on hosted runners is the pre-10.15 *SDK* case, since that needs SDKs
from third-party mirrors — not something I'd put in this repo's CI.

I kept this patch as small as possible on purpose; CI would be a separate PR.

File: subprocess.h
Comment (sheredom) [reply subprocess.h:1243]: https://github.com/sheredom/subprocess.h/pull/110

**Comment by sheredom** [comment]
Would happily accept a CI patch to test more things for sure. I just don't want to inadvertently break anyone if I can help it!
